<style>
textarea {resize: none; width: 600px; height: 100px;}
</style>
<div class="wrap">
	<div id="icon-options-general" class="icon32"></div>
	<h2><?php _e('User Profile Widget', 'BTCRS')?></h2>
	<?php if(isset($message)):?>
		<?php if(isset($error)):?>
			<div class="error below-h2">
				<p><strong><?php _e('ERROR: ', 'BTCRS')?></strong><?php echo $message?></p>	
			</div>
		<?php else:?>
			<div id="setting-error-settings_updated" class="updated settings-error">
				<p><strong><?php echo $message?></strong></p>
			</div>
		<?php endif ?>
	<?php endif ?>
	<br/>
	<form method="post">
		<input type="hidden" value="update" name="action">
		<table class="form-table">
			<tbody>
				<tr valign="top">
					<th scope="row">
						<label for="user_profile_html"><?php _e('User Profile Widget HTML', 'BTCRS')?></label>
					</th>
					<td>
						<textarea name="user_profile_html"><?php echo stripslashes(get_option('user_profile_html'))?></textarea>
					</td>
				</tr>
			</tbody>
		</table>


		<p class="submit"><input type="submit" value="<?php _e('Save Changes', 'BTCRS')?>" class="button-primary" id="submit" name="submit"></p>
	</form>
</div>